export const ImgList = [
  { Category: "Eye", Num: 1 },
  { Category: "Eye", Num: 2 },
  { Category: "Eye", Num: 3 },
  { Category: "Eye", Num: 4 },
  { Category: "Eye", Num: 5 },
  { Category: "Eye", Num: 6 },
  { Category: "Mouth", Num: 1 },
  { Category: "Mouth", Num: 2 },
  { Category: "Mouth", Num: 3 },
  { Category: "Mouth", Num: 4 },
  { Category: "Mouth", Num: 5 },
  { Category: "Back", Num: 1 },
  { Category: "Back", Num: 2 },
  { Category: "Back", Num: 3 },
  { Category: "Back", Num: 4 },
  { Category: "Back", Num: 5 },
  { Category: "Back", Num: 6 },
  { Category: "Back", Num: 7 },
  { Category: "Hair", Num: 1 },
  { Category: "Hair", Num: 2 },
  { Category: "Hair", Num: 3 },
  { Category: "Hair", Num: 4 },
  { Category: "Hair", Num: 5 },
  { Category: "Hair", Num: 6 },
];
